### ISSUE TITLE
make "run" commands explicit in the entrypoint

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#16]
instead of the current:

```
    entrypoint:
        - ["/golem/run/simulate_observations_ctl.py", "--start"]
        - ["/bin/sh", "-c", "sleep 15" ]
        - [ "/golem/run/simple_service.py", "--stats"]
```

```
    entrypoint:
        - run:
           - ["/golem/run/simulate_observations_ctl.py", "--start"]
        - run:
            - ["/bin/sh", "-c", "sleep 15" ]
        - run:
            - [ "/golem/run/simple_service.py", "--stats"]
```

**Comment by johny-b** [comment]
Consider: maybe both options could run?

**Comment by shadeofblue** [comment]
this is the implemented syntax as per: https://github.com/golemfactory/golem-architecture/pull/39#issuecomment-1245416018

```
    init:
      - test:
          args: ["/bin/rm", "/var/log/nginx/access.log", "/var/log/nginx/error.log"]
          from: "aa"
          to: "b"
      - aaa:
          args: ["/bin/rm", "/var/log/nginx/access.log", "/var/log/nginx/error.log"]
          from: "aa"
          to: "b"

    init: ["/docker-entrypoint.sh"]

    init:
      - run:
          args:
            - "/docker-entrypoint.sh"
 
    init:
        - ["/docker-entrypoint.sh"]
        - ["/bin/chmod", "a+x", "/"]
        - ["/bin/sh", "-c", 'echo "Hello from inside Golem!" > /usr/share/nginx/html/index.html']
```

and obviously, currently the only supported command is `run`
