### ISSUE TITLE
support for multiple instances of a single service

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#21]
e.g.

```
nodes:
  http:
    payload: "nginx"
    entrypoint:
        ...
    network:
      "default"
    http_proxy:
      ports:
        - "80"
    cardinality: 5
```

vs

```
nodes:
  http:
    payload: "nginx"
    entrypoint:
        ...
    network:
      "default"
    http_proxy:
      ports:
        - "80"
    parametrize:
      - foo: "val"
        bar: 5
      - foo: "val2"
        bar: 2
```

**Comment by shadeofblue** [comment]
```
nodes:
  http:
    payload: "nginx"
    entrypoint:
        ...
    network:
      "default"
    http_proxy:
      ports:
        - "80"
    ip:
      - "192.168.0.2"
      - "192.168.0.3"
```
