### ISSUE TITLE
meta data descriptor support

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#33]
```
meta:
  name: "Cośtam app"
  description: "sdljasldkjfsal;kfjsa;ldkas;lkdfj asd;lkf jas"
  author: "GolemFactory"
  version: "0.1.0"
```
