### ISSUE TITLE
support for `depends-on`

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#34]
a'la docker-compose:

```
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      db_data:
```
