### ISSUE TITLE
`dapp-runner` doesn't detect/report network IP collissions

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#58]
misreports the specific service as `running` despite the fact that no commands had ever been executed in the container

to reproduce, launch the service on `192.168.0.1` -> this address is automatically assigned as the _requestor's_ ... 

e.g.

```
nodes:
  cache:
    payload: "cache"
    init:
      - ["/bin/bash", "-c", "redis-server --bind 0.0.0.0 --loglevel debug > /dev/null &"]
    http_proxy:
      ports:
        - "6379"
    network: "default"
    ip:
      - "192.168.0.1"
```

the providers can use addresses other than the first one on a given network but dapp-runner should still properly detect/report this issue
