### ISSUE TITLE
add `SocketProxy` support

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#61]
Why:
* enable direct access to tcp services hosted inside dapps (eg db)

What:
* [x] add support to the descriptor and to the runner code
* [ ] update the GAP https://github.com/golemfactory/golem-architecture/pull/39

**Comment by shadeofblue** [comment]
proposed solution:


```
nodes:
  db:
    payload: "db"
    init:
      - run:
          args:
            - "/bin/run_rqlite.sh"
    proxy:
      ports:
        - "4001" 
    network: "default"
    ip:
      - "192.168.0.2"
  http:
    payload: "http"
    init:
      - run:
          args: ["/bin/bash", "-c", "cd /webapp && python app.py --db-address 192.168.0.2 --db-port 4001 initdb"]
      - run:
          args: ["/bin/bash", "-c", "cd /webapp && python app.py --db-address 192.168.0.2 --db-port 4001 run > /webapp/out 2> /webapp/err &"]
    http_proxy:
      ports:
        - "5000"  # specify just the remote port, allow the local port to be automatically chosen
    network: "default"
    ip:
      - "192.168.0.3"
    depends_on:
      - "db"
```
