### ISSUE TITLE
automated manifest creation support

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#64]
RATIONALE:

**Any outbound network access requires a payload manifest**

- Manifest is always required even if the addresses accessed are included in the whitelist
- the construction of a manifest is a significant additional effort
    - we need to figure out the most minimal possible manifest
    - automate its creation based on the app descriptor, using yapapi's manifest support, based on: https://github.com/golemfactory/yapapi/pull/1010

Proposed syntax: 

```

payloads:
  external-api-request:
    runtime: "vm/manifest"  # or should it be `vm` ? 
    params:
      image_hash: "16ad039c00f60a48c76d0644c96ccba63b13296d140477c736512127"
      outbound:
        urls:
          - "https://api.coingecko.com"
          - "https://httpbin.org"

```

(implicit inlusion of `inet` and `manifest-support` capabilities)

depends on: https://github.com/golemfactory/yapapi/pull/1010
