### ISSUE TITLE
`api_url` and `gsb_url` configuration keys are not used

### ISSUE THREAD

**Issue by lucekdudek** [golemfactory/dapp-runner#66]
`default.yaml` specifics `api_url` and `gsb_url` but those are not used.
```yml
yagna:
#  api_url: "http://localhost:7465"
#  gsb_url: "http://localhost:9999"
  app_key: "$YAGNA_APPKEY"
  subnet_tag: "devnet-beta"
```
