### ISSUE TITLE
`environment` support for commands run on the providers

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#73]
we'd like add an `environment` definition similar to what's available in docker-compose

e.g.

```
nodes:
  backend:
    payload: "backend"
    environment: 
      PROVIDER_ADDRESS: "http://bor.golem.network/"
      MONGO_DB_CONNECTION_STRING: "mongodb://192.168.0.2:27017"
...

```

it should be passed to all commands that are executed on the given node (Service)

yapapi should support this:

https://github.com/golemfactory/yapapi/blob/master/yapapi/script/__init__.py#L154

but maybe first we should perform a quick spike:
* https://github.com/golemfactory/yapapi/issues/1071
